### ISSUE TITLE
Consider renaming this license

### ISSUE THREAD

**Issue by pombredanne** [CastillaSBC/Castilla-License#1]
This is unlikely acceptable and likely misleading to claim this license still to be an Apache license. See https://www.apache.org/foundation/license-faq.html#mod-license

> **May I re-use (and modify) the Apache License 2.0 itself?**
> 
> You may re-use our license unchanged, and also modify it.
> 
> If you modify it, you are on your own from a legal point of view, and the result is NOT the Apache License, just a new license inspired by ours.
> 
> This means that the terms 'Apache License', 'Apache', and any similar references to the ASF cannot appear in your modified license, other than to state that it differs from the original.
> 
> Also, you cannot use 'Apache' in the name of the modified license. Names like "Apache License with such-and-such clause", for example, are not acceptable, as they cause confusion.
> 
> Creating a new license is a non-trivial task. If you do that we recommend that you get your own legal advice.

**Comment by bluefield-creator** [comment]
You are totally right. Changes will be done. Thanks for the info.

**Comment by bluefield-creator** [comment]
Fixed in latest commit. Release will happen later today.

 584c10fc1f79895d6857afd9f01fc0887d323896
